# Generated by Django 3.1.5 on 2021-01-27 16:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receptionist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pharmacist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], default='M', max_length=1)),
                ('birthday', models.DateField()),
                ('phone_number', models.CharField(max_length=12)),
                ('emergency_phone', models.CharField(max_length=12)),
                ('height', models.PositiveIntegerField()),
                ('weight', models.PositiveIntegerField()),
                ('blood_group', models.CharField(choices=[('NA', "Don't Know"), ('O+', 'O Positive'), ('O-', 'O Negative'), ('A+', 'A Positive'), ('A-', 'A Negative'), ('B+', 'B Positive'), ('B-', 'B Negative'), ('AB+', 'AB Positive'), ('AB-', 'AB Negative')], default='NA', max_length=3)),
                ('past_diseases', models.CharField(blank=True, choices=[('1', 'Alzheimer’s'), ('2', 'Arthritis'), ('3', 'Asthma'), ('4', 'Blood Diseases'), ('5', 'Cancer'), ('6', 'Diabetes'), ('7', 'Heart Disease'), ('8', 'Hyper Tension'), ('9', 'Kidney Disease'), ('10', 'Liver Diseases'), ('11', 'Osteoporosis'), ('12', 'Pneumonia and Influenza'), ('13', 'Psychiatric Diseases'), ('14', 'Stroke and Cerebrovascular diseases'), ('15', 'Tuberculosis')], max_length=2, null=True)),
                ('other_diseases', models.CharField(default='nil', max_length=20)),
                ('allergies', models.CharField(default='nil', max_length=20, null=True)),
                ('staff', models.BooleanField(default=False)),
                ('prescriptions', models.ManyToManyField(blank=True, related_name='history', to='hc.Prescription')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('T', 'Transgender')], max_length=1)),
                ('available', models.BooleanField(default=False)),
                ('specialization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='specializations', to='hc.doctorspecialization')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
